---
  - hosts: all
    become: true
    tasks:
      - name: Update package list
        apt: update_cache=yes

      - name: Install packages
        apt: name={{ item }} state=latest
        with_items:
          - python-pip
          - nginx
          - sqlite

      - name: PIP install
        pip: requirements=/vagrant/app/Requirements.txt
